version: '3'
services:
  laravel:
    container_name: laravel1
    command: /usr/local/bin/run.sh
    env_file:
      - ./.env
    build: .
    ports:
      - 8089:8000
      - 5173:5173
      - 5174:5174
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel_network
  mysql:
    container_name: laravel_mysql
    image: mysql:8.0.32
    ports: 
      - 3309:3306
    env_file:
      - ./.mysql_env
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel_network
  mongo:
    container_name: laravel_mongo
    image: mongo:7.0
    volumes:
      - ./mongo_data:/data/db
    env_file:
      - ./.mongo_env
    networks:
      - laravel_network
  mongo-express:
    container_name: laravel_mongo_express
    image: mongo-express:1.0.0-18-alpine3.18
    depends_on:
      - mongo
    restart: always
    ports:
      - 8084:8081
    env_file:
      - ./.mongo_env
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge