version: '3'
services:
  laravel:
    container_name: laravel1
    command: /usr/local/bin/run.sh
    env_file:
      - ./.env
    build: .
    ports:
      - 8089:8000
      - 5173:5173
      - 5174:5174
    volumes:
      - ./src:/var/www/html
      - ./docker-php-upload.ini:/usr/local/etc/php/conf.d/docker-php-upload.ini
    networks:
      - laravel_network
  mysql:
    container_name: laravel_mysql
    image: mysql:8.0.32
    ports: 
      - 3309:3306
    env_file:
      - ./.mysql_env
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - laravel_network
  mongo1:
    container_name: laravel_mongo1
    image: mongo:7.0
    command: mongod --config /etc/mongo/mongod.conf --auth
    # command: sleep 86400 &
    volumes:
      - ./mongo_data1:/data/db
      - ./mongo_config/mongo1:/etc/mongo
      - ./mongo_key:/data/configdb/mongo_key
    env_file:
      - ./.mongo_env
    expose:
      - 27017
    networks:
      - laravel_network
  mongo2:
    container_name: laravel_mongo2
    image: mongo:7.0
    command: mongod --config /etc/mongo/mongod.conf --auth
    volumes:
      - ./mongo_data2:/data/db
      - ./mongo_config/mongo2:/etc/mongo
      - ./mongo_key:/data/configdb/mongo_key
    env_file:
      - ./.mongo_env
    expose:
      - 27017
    networks:
      - laravel_network
  mongo-express:
    container_name: laravel_mongo_express
    image: mongo-express:1.0.0-18-alpine3.18
    depends_on:
      - mongo1
      - mongo2
    restart: always
    ports:
      - 8084:8081
    env_file:
      - ./.mongo_env
    networks:
      - laravel_network
networks:
  laravel_network:
    driver: bridge